import type { Metadata } from "next";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from "@mantine/core";
import "./globals.css";
import '@mantine/notifications/styles.css';
import { Notifications } from "@mantine/notifications";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: 'Kanit, sans-serif',
  fontFamilyMonospace: 'Monaco, Courier, monospace',
  headings: { fontFamily: 'Greycliff CF, sans-serif' },
  scale: 1.1,
  breakpoints: {
    lg: '1380px',
  }
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body >
        <MantineProvider theme={theme}>
          <Notifications />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
